"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Building2, ChevronRight, Plus, Search, ShieldCheck, Users, X } from "lucide-react";
import { createBrowserClient } from "@supabase/ssr";

type School = {
  id: string; name: string; region: string | null; email_domain: string | null;
  school_type: string | null; student_count: number | null; status: string;
  plan: string; funding_type: string; created_at: string; updated_at: string;
  memberCount: number; adminCount: number; teacherCount: number;
};

const PLAN_LABELS: Record<string, string> = { free: "Free", starter: "Starter", school: "School", growth: "Growth", enterprise: "Enterprise" };
const FUNDING_LABELS: Record<string, string> = { sponsored: "Sponsored", grant: "Förderung" };
const TYPE_LABELS: Record<string, string> = { grundschule: "Grundschule", hauptschule: "Hauptschule", realschule: "Realschule", gesamtschule: "Gesamtschule", gymnasium: "Gymnasium", berufskolleg: "Berufskolleg", sonstige: "Sonstige" };
function client() { return createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!); }

export function SchoolAdminWorkspace({ initialSchools }: { initialSchools: School[] }) {
  const [schools, setSchools] = useState(initialSchools);
  const [query, setQuery] = useState(""); const [planFilter, setPlanFilter] = useState("all"); const [fundingFilter, setFundingFilter] = useState("all");
  const [showCreate, setShowCreate] = useState(false); const [name, setName] = useState(""); const [region, setRegion] = useState(""); const [domain, setDomain] = useState(""); const [schoolType, setSchoolType] = useState("gymnasium"); const [students, setStudents] = useState(""); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null);

  const filtered = useMemo(() => schools.filter((school) => {
    const haystack = `${school.name} ${school.region ?? ""} ${school.email_domain ?? ""}`.toLocaleLowerCase("de-DE");
    return haystack.includes(query.trim().toLocaleLowerCase("de-DE")) && (planFilter === "all" || school.plan === planFilter) && (fundingFilter === "all" || school.funding_type === fundingFilter);
  }), [schools, query, planFilter, fundingFilter]);

  async function createSchool(e: React.FormEvent) {
    e.preventDefault(); setPending(true); setMessage(null);
    try {
      const supabase = client(); const { data: { session } } = await supabase.auth.getSession();
      const response = await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/provision-school`, { method: "POST", headers: { Authorization: `Bearer ${session?.access_token}`, "Content-Type": "application/json" }, body: JSON.stringify({ name, region, emailDomain: domain }) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Schule konnte nicht angelegt werden");
      const studentCount = students ? Number(students) : null;
      const { error } = await supabase.from("schools").update({ school_type: schoolType, student_count: studentCount }).eq("id", data.school.id); if (error) throw error;
      setSchools((current) => [...current, { ...data.school, school_type: schoolType, student_count: studentCount, status: "active", plan: "free", funding_type: "none", updated_at: data.school.created_at, memberCount: 0, adminCount: 0, teacherCount: 0 }].sort((a, b) => a.name.localeCompare(b.name)));
      setShowCreate(false); setName(""); setRegion(""); setDomain(""); setStudents(""); setMessage("Schule angelegt.");
    } catch (error) { setMessage(error instanceof Error ? error.message : "Fehler beim Anlegen"); } finally { setPending(false); }
  }

  return <>
    <section className="grid gap-3 sm:grid-cols-3 mb-7"><div className="rounded-2xl border border-border bg-panel p-4"><p className="text-xs text-slate-400">Schulen</p><p className="mt-1 text-2xl font-semibold text-slate-900">{schools.length}</p></div><div className="rounded-2xl border border-border bg-panel p-4"><p className="text-xs text-slate-400">Aktive Personen</p><p className="mt-1 text-2xl font-semibold text-slate-900">{schools.reduce((sum, s) => sum + s.memberCount, 0)}</p></div><div className="rounded-2xl border border-border bg-panel p-4"><p className="text-xs text-slate-400">Sponsored / Förderung</p><p className="mt-1 text-2xl font-semibold text-slate-900">{schools.filter((s) => s.funding_type !== "none").length}</p></div></section>
    <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between mb-5"><div className="relative flex-1 max-w-xl"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Schule, Region oder Domain suchen …" className="w-full rounded-xl border border-border bg-panel py-2.5 pl-9 pr-3 text-sm outline-none focus:border-accent" /></div><div className="flex flex-wrap gap-2"><select value={planFilter} onChange={(e) => setPlanFilter(e.target.value)} className="rounded-xl border border-border bg-panel px-3 py-2.5 text-sm"><option value="all">Alle Pläne</option>{Object.entries(PLAN_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><select value={fundingFilter} onChange={(e) => setFundingFilter(e.target.value)} className="rounded-xl border border-border bg-panel px-3 py-2.5 text-sm"><option value="all">Alle Förderungen</option><option value="sponsored">Sponsored</option><option value="grant">Förderung</option><option value="none">Keine</option></select><button type="button" onClick={() => setShowCreate(true)} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-medium text-white"><Plus className="h-4 w-4" /> Neue Schule</button></div></div>
    {message && <div className="mb-5 rounded-xl border border-border bg-panel px-4 py-3 text-sm text-slate-700">{message}</div>}
    {filtered.length === 0 ? <div className="rounded-3xl border border-dashed border-border bg-panel p-14 text-center"><Building2 className="mx-auto h-8 w-8 text-slate-300" /><p className="mt-3 font-medium text-slate-800">Keine Schulen gefunden</p><p className="mt-1 text-sm text-slate-500">Passe Suche oder Filter an.</p></div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((school) => <Link key={school.id} href={`/schools/${school.id}`} className="group rounded-3xl border border-border bg-panel p-5 transition hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-lg"><div className="flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-canvas text-slate-500"><Building2 className="h-5 w-5" /></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${school.status === "active" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{school.status === "active" ? "Aktiv" : school.status}</span></div><h2 className="mt-5 text-lg font-semibold text-slate-900">{school.name}</h2><p className="mt-1 text-sm text-slate-500">{TYPE_LABELS[school.school_type ?? ""] ?? school.school_type ?? "Schulform nicht hinterlegt"}{school.region ? ` · ${school.region}` : ""}</p><p className="mt-2 truncate text-xs text-slate-400">{school.email_domain ? `@${school.email_domain}` : "Keine Schul-Domain hinterlegt"}</p><div className="mt-5 grid grid-cols-3 gap-2 border-t border-border pt-4"><div><p className="text-[11px] text-slate-400">Schüler</p><p className="mt-0.5 text-sm font-semibold text-slate-800">{school.student_count?.toLocaleString("de-DE") ?? "—"}</p></div><div><p className="text-[11px] text-slate-400">Personen</p><p className="mt-0.5 text-sm font-semibold text-slate-800">{school.memberCount}</p></div><div><p className="text-[11px] text-slate-400">Plan</p><p className="mt-0.5 text-sm font-semibold text-slate-800">{PLAN_LABELS[school.plan] ?? school.plan}</p></div></div><div className="mt-4 flex items-center gap-2 text-xs text-slate-400"><ShieldCheck className="h-3.5 w-3.5" /> Domain geschützt{school.funding_type !== "none" && <span className="ml-auto rounded-full bg-accent/10 px-2 py-1 font-medium text-accent">{FUNDING_LABELS[school.funding_type]}</span>}<Users className="ml-2 h-3.5 w-3.5" /><span>Verwalten</span><ChevronRight className="h-4 w-4 transition group-hover:translate-x-0.5" /></div></Link>)}</div>}
    {showCreate && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/30 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-3xl border border-border bg-panel p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-accent">Neue Organisation</p><h2 className="mt-1 text-xl font-semibold text-slate-900">Schule anlegen</h2></div><button type="button" onClick={() => setShowCreate(false)} className="text-slate-400">×</button></div><form onSubmit={createSchool} className="mt-6 space-y-4"><label className="block text-sm font-medium text-slate-700">Schulname<input required value={name} onChange={(e) => setName(e.target.value)} className="mt-1.5 w-full rounded-xl border border-border px-3 py-2.5 text-sm" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium text-slate-700">Schulform<select value={schoolType} onChange={(e) => setSchoolType(e.target.value)} className="mt-1.5 w-full rounded-xl border border-border px-3 py-2.5 text-sm">{Object.entries(TYPE_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="block text-sm font-medium text-slate-700">Schülerzahl<input type="number" min="0" value={students} onChange={(e) => setStudents(e.target.value)} className="mt-1.5 w-full rounded-xl border border-border px-3 py-2.5 text-sm" /></label></div><label className="block text-sm font-medium text-slate-700">Region<input value={region} onChange={(e) => setRegion(e.target.value)} className="mt-1.5 w-full rounded-xl border border-border px-3 py-2.5 text-sm" /></label><label className="block text-sm font-medium text-slate-700">Schul-Domain<input value={domain} onChange={(e) => setDomain(e.target.value)} placeholder="schule.de" className="mt-1.5 w-full rounded-xl border border-border px-3 py-2.5 text-sm" /></label><div className="flex justify-end gap-2 pt-2"><button type="button" onClick={() => setShowCreate(false)} className="rounded-xl border border-border px-4 py-2.5 text-sm">Abbrechen</button><button disabled={pending} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">{pending ? "Wird angelegt …" : "Schule anlegen"}</button></div></form></div></div>}
  </>;
}
